### ISSUE TITLE
Grabber adding query and fragment to file names downloaded through curl

### ISSUE THREAD

**Issue by hopejr** [bojanra/cherryTool#1]
On line 302 of Grabber.pm, it's adding the query string and fragment to the filename. This is problematic when downloading from somewhere like DropBox where to download the file via curl one needs to add ?dl=1 to the URL. If the file is a spreadsheet, then the Spreadsheet::Read ReadData() function can't work out what type of file it is (it uses the file extension) and fails.

**Comment by bojanra** [comment]
Concatenating query and fragment to the file path is used because in some cases the date information is encoded in the url. 
The problem with the ReadData() function is solved by moving the extension from the path to the end of the string. You can upgrade your installation.

**Comment by hopejr** [comment]
Great, that's fixed it. Thank you.
